Update ncp-update
Fix backwards_updates so that a semi updated system
can keep up to date even after the cleanup of update.sh
and get back on track of the newer updates.
Merge group of update.sh commits before and after the
cleanup

diff --git a/bin/ncp-update b/bin/ncp-update
--- a/bin/ncp-update
+++ b/bin/ncp-update
@@ -17,10 +17,47 @@
     exit 1
   }
 
-  [[ -f /.ncp-image ]] || cd "$TMPDIR"         # update locally during build
+  a[[ -f /.ncp-image ]] || cd "$TMPDIR"         # update locally during build
 
   echo -e "Performing updates"
-  ./update.sh || exit 1
+
+  #fix later. testing now to update versions before latest cleanup
+  latest_checkpoint="1.10.11"
+  MAJOR=1 #$( grep -oP "\d+\.\d+\.\d+" $latest_checkpoint | cut -d. -f1 )
+  MINOR=10 #$( grep -oP "\d+\.\d+\.\d+" $latest_checkpoint | cut -d. -f2 )
+  PATCH=11 #$( grep -oP "\d+\.\d+\.\d+" $latest_checkpoint | cut -d. -f3 )
+
+  MAJ=$( grep -oP "\d+\.\d+\.\d+" /usr/local/etc/ncp-version | cut -d. -f1 )
+  MIN=$( grep -oP "\d+\.\d+\.\d+" /usr/local/etc/ncp-version | cut -d. -f2 )
+  PAT=$( grep -oP "\d+\.\d+\.\d+" /usr/local/etc/ncp-version | cut -d. -f3 )
+
+  BACKWARDS_UPDATES=false
+
+  if [ "$MAJOR" -gt "$MAJ" ]; then
+    BACKWARDS_UPDATES=true
+  elif [ "$MAJOR" -eq "$MAJ" ] && [ "$MINOR" -gt "$MIN" ]; then
+    BACKWARDS_UPDATES=true
+  elif [ "$MAJOR" -eq "$MAJ" ] && [ "$MINOR" -eq "$MIN" ] && [ "$PATCH" -gt "$PAT" ]; then
+    BACKWARDS_UPDATES=true
+  fi
+
+  if $BACKWARDS_UPDATES ; then
+    updates_list=(update_1_10_0_to_1_10_11_.sh update_1_10_12_to_1_13_2_.sh)
+
+    for update_file in "${updates_list[@]}"; do
+      MAJ=$(echo ${update_file} | cut -d'_' -f2)
+      MIN=$(echo ${update_file} | cut -d'_' -f3)
+      PAT=$(echo ${update_file} | cut -d'_' -f4)
+      tag_update="v${MAJ}.${MIN}.${P}"
+      git checkout ${tag_update}
+
+      cp $update_file ./update.sh		#where is my updates folder?
+
+      ./update.sh || exit 1
+    done
+  else
+    ./update.sh || exit 1
+  fi
 
   cd "$TMPDIR"
   VER=$( git describe --always --tags | grep -oP "v\d+\.\d+\.\d+" )
