Update ncp-update.sh
Fix backwards updates by executing binary search
to find the starting checkpoint of the updates
that we need to apply to an outdated system

diff --git a/bin/ncp-update b/bin/ncp-update
--- a/bin/ncp-update
+++ b/bin/ncp-update
@@ -17,20 +17,32 @@
     exit 1
   }
 
-  a[[ -f /.ncp-image ]] || cd "$TMPDIR"         # update locally during build
+  [[ -f /.ncp-image ]] || cd "$TMPDIR"         # update locally during build
 
   echo -e "Performing updates"
 
-  #fix later. testing now to update versions before latest cleanup
-  latest_checkpoint="1.10.11"
-  MAJOR=1 #$( grep -oP "\d+\.\d+\.\d+" $latest_checkpoint | cut -d. -f1 )
-  MINOR=10 #$( grep -oP "\d+\.\d+\.\d+" $latest_checkpoint | cut -d. -f2 )
-  PATCH=11 #$( grep -oP "\d+\.\d+\.\d+" $latest_checkpoint | cut -d. -f3 )
+  # Latest checkpoint is the version right before the latest cleanup of update.sh
+  #latest_checkpoint="1.10.11" # Static insert now, fix later
+  # Get the array of updates dir
+  i=0
+  while read line ; do
+    updates_list[ $i ]="$line"
+    (( i++ ))
+  done < <( ls updates )
+
+  # The latest checkpoint is the newer version in updates dir
+  latest_checkpoint=updates_list[i-1]
+
+  # Compare current version with latest checkpoint to see if we need backwards updates
+  MAJOR=$( grep -oP "\d+\.\d+\.\d+" $latest_checkpoint | cut -d. -f1 )
+  MINOR=$( grep -oP "\d+\.\d+\.\d+" $latest_checkpoint | cut -d. -f2 )
+  PATCH=$( grep -oP "\d+\.\d+\.\d+" $latest_checkpoint | cut -d. -f3 )
 
   MAJ=$( grep -oP "\d+\.\d+\.\d+" /usr/local/etc/ncp-version | cut -d. -f1 )
   MIN=$( grep -oP "\d+\.\d+\.\d+" /usr/local/etc/ncp-version | cut -d. -f2 )
   PAT=$( grep -oP "\d+\.\d+\.\d+" /usr/local/etc/ncp-version | cut -d. -f3 )
 
+  # If the system is beyond the latest checkpoint there is no need to get in the loop
   BACKWARDS_UPDATES=false
 
   if [ "$MAJOR" -gt "$MAJ" ]; then
@@ -42,20 +54,106 @@
   fi
 
   if $BACKWARDS_UPDATES ; then
-    updates_list=(update_1_10_0_to_1_10_11_.sh update_1_10_12_to_1_13_2_.sh)
 
-    for update_file in "${updates_list[@]}"; do
-      MAJ=$(echo ${update_file} | cut -d'_' -f2)
-      MIN=$(echo ${update_file} | cut -d'_' -f3)
-      PAT=$(echo ${update_file} | cut -d'_' -f4)
-      tag_update="v${MAJ}.${MIN}.${P}"
-      git checkout ${tag_update}
+    # Execute a series of updates of older versions
 
-      cp $update_file ./update.sh		#where is my updates folder?
+    # Binary search to find the right checkpoint to begin the updates
+    
+    starting_checkpoint=0
+    len=${#updates_list[@]}
+    end_of_list=$(expr $len - 1)
+    
+    lower_bound=0
+    upper_bound=$end_of_list
+    while [ $lower_bound -le $upper_bound ]; do
+      x=$(expr $upper_bound + $lower_bound)
+      mid=$(expr $x / 2 )
 
-      ./update.sh || exit 1
+      #Compare mid's version with current version
+      MAJOR=$( grep -oP "\d+\.\d+\.\d+" $updates_list[mid] | cut -d. -f1 )
+      MINOR=$( grep -oP "\d+\.\d+\.\d+" $updates_list[mid] | cut -d. -f2 )
+      PATCH=$( grep -oP "\d+\.\d+\.\d+" $updates_list[mid] | cut -d. -f3 )
+      
+      apply_update=false
+      if [ "$MAJOR" -gt "$MAJ" ]; then
+        apply_update=true
+      elif [ "$MAJOR" -eq "$MAJ" ] && [ "$MINOR" -gt "$MIN" ]; then
+        apply_update=true
+      elif [ "$MAJOR" -eq "$MAJ" ] && [ "$MINOR" -eq "$MIN" ] && [ "$PATCH" -gt "$PAT" ]; then
+        apply_update=true
+      fi
+
+      if $apply_update ; then 
+      # Mid's version update is applicable to the current version
+      # Check if the previous checkpoint (mid-1) has already been applied
+
+        previous=$(expr $mid - 1)
+        if [ "$mid" -gt 0 ] ; then
+          #Compare previous's version with current version
+          MAJOR_=$( grep -oP "\d+\.\d+\.\d+" $updates_list[previous] | cut -d. -f1 )
+          MINOR_=$( grep -oP "\d+\.\d+\.\d+" $updates_list[previous] | cut -d. -f2 )
+          PATCH_=$( grep -oP "\d+\.\d+\.\d+" $updates_list[previous] | cut -d. -f3 )
+      
+          applied=true
+          if [ "$MAJOR_" -gt "$MAJ" ]; then
+            applied=false
+          elif [ "$MAJOR_" -eq "$MAJ" ] && [ "$MINOR_" -gt "$MIN" ]; then
+            applied=false
+          elif [ "$MAJOR_" -eq "$MAJ" ] && [ "$MINOR_" -eq "$MIN" ] && [ "$PATCH_" -gt "$PAT" ]; then
+            applied=false
+          fi
+
+	  # If the previous checkpoint has already been applied then mid is the beggining checkpoint for the current version
+	  if $applied ; then
+            starting_checkpoint=$mid
+	    break
+	  fi
+        else
+          # mid is at 0
+	  starting_checkpoint=$mid
+	  break
+	fi
+	# Continue searching
+	upper_bound=$(expr $mid - 1)
+
+      else #[ $item -gt ${arr[$mid]} ] ; then
+	# Mid's version update is not applicable to the current version (has already been applied)
+        # Check if the next checkpoint (mid+1) has already been applied
+
+	next=$(expr mid + 1)
+        #Compare next's version with current version
+        MAJOR_=$( grep -oP "\d+\.\d+\.\d+" $updates_list[next] | cut -d. -f1 )
+        MINOR_=$( grep -oP "\d+\.\d+\.\d+" $updates_list[next] | cut -d. -f2 )
+        PATCH_=$( grep -oP "\d+\.\d+\.\d+" $updates_list[next] | cut -d. -f3 )
+      
+        applied=false
+        if [ "$MAJOR_" -gt "$MAJ" ]; then
+          applied=true
+        elif [ "$MAJOR_" -eq "$MAJ" ] && [ "$MINOR_" -gt "$MIN" ]; then
+          applied=true
+        elif [ "$MAJOR_" -eq "$MAJ" ] && [ "$MINOR_" -eq "$MIN" ] && [ "$PATCH_" -gt "$PAT" ]; then
+          applied=true
+        fi
+
+	if $applied ; then
+	  # Continue searching
+          lower_bound=$(expr $mid + 1)
+	else
+          # The next version is the starting checkpoint
+	  starting_checkpoint=$next
+	  break
+	fi
+      fi
+    done
+
+    for(( i=$starting_checkpoint; i<=$end_of_list; i++)); do
+      update_file=${updates_list[i]}
+      #tag_update="v${MAJ}.${MIN}.${PAT}"
+      #git checkout ${tag_update}
+      ./${update_file} || exit 1
     done
   else
+    # Up to date system updates
     ./update.sh || exit 1
   fi
 
